### PR TITLE
7 refactor test_five_models.ipynb

### PR DESCRIPTION
**Pull request by eriktks**
Ref: #7 

Refactored notebook test_five_models.ipynb: 
* split main code block in smaller blocks
* added more comments

To test: run notebook and verify that everything works

Note: I tried to add [reviewnb.com](https://reviewnb.com)'s notebook reviewer but could not do that for this repository because it was not in my personal organization

### CODE REVIEW

**Review by sverhoeven — CHANGES_REQUESTED** [review]
I like that you put the sub plots in a single column that makes it easier to see how they combine.

Reviewed on https://app.reviewnb.com/sequgen/notebooks/pull/13/

Why was printing of version of sequgen removed?

**Comment by eriktks** [comment]
Printing the sequgen version was removed because I did not see the benefit of having it, from a user point of view. Probably I am missing something here.

Thanks for adding this repository to Reviewnb. However, I do not see a review there, only Notebooks, Commits and Pull Requests.

**Review by sverhoeven — APPROVED** [review]
OK, pinning sequgen version in https://github.com/sequgen/notebooks/blob/85475618e30e92213e16f4dbd1eee5ebb62b8d8c/requirements.txt#L1 is propably easier.

I only used reviewnb to look at the diff as I could not comment on the deleted cell.
I think when a new PR created then Reviewnb adds a comment with a link.

**Comment by eriktks** [comment]
Ok, thanks!

**Pull request merged**
